---
title: Verification Plan for Super Learner Risk Score Calculations
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

Project directory: `correlates_reporting/base_riskscore`

Specifications: `correlates_reporting/base_riskscore/risk_score_specification.Rmd`

Other Background Information: N/A

### Verification  Sign-Off

```{r signatures, echo = FALSE, message = FALSE, tidy = FALSE, cache = FALSE, results = 'asis'}
library(knitr)
library(kableExtra)
library(tibble)

options(kableExtra.latex.load_packages = FALSE, 
        knitr.table.format = "latex",
        knitr.kable.NA = '',
        width = 40,
        usethis.quiet = TRUE)

signature_table <- function(people){
  # check that the tables have correct variables
  if (!all(c("role", "name") %in% tolower(names(people)))) {
    stop(paste0("people table must have variables: role and name. ",
                "Contains: ", paste0(tolower(names(people)), collapse = ", ")))
  }
  
  people$signature <- NA
  people$date <- NA
  names(people) <- tolower(names(people))
  people[, c("role", "name", "signature", "date")] %>% 
  kable(col.names = c("Role", "Name", "Signature", "Date"),
        escape = FALSE, booktabs = FALSE) %>% 
    kable_styling(full_width = FALSE, position = "left") %>% 
    row_spec(0, background = rgb(184, 204, 228, maxColorValue = 255)) %>% 
    column_spec(1, width = "9em", border_left = TRUE) %>% 
    column_spec(2, width = "11em") %>% 
    column_spec(3, width = "15em") %>% 
    column_spec(4, width = "8em", border_right = TRUE)
}

tibble::tribble(
  ~ name,                ~ role,
  "Dr. Peter Gilbert",  "Manager",
  "Bhavesh Borate",     "Specifier/Programmer",
  "Dr. David Benkeser", "Tester"
) %>% 
  signature_table()

```

## Verification Procedure

Verification for the super learner risk score calculations generated in support of the CoVPN correlates will be based on a risk based approach. The risk of the calculations is determined to be high as it will be used to drive decision making and used throughout the Correlates of Risk calculations. The calculations will be verified by someone other than the original programmer (the tester). 

For independent double programming, the tester will independently generate the same dataset based on the specification. They will then programmatically verify the values presented in the original dataset match the ones generated by the verification code, and produce an output file that shows that the results match. 

The final output data generated by code in the `base_riskscore` folder are determined to be high risk, and thus will all be independently double programmed.

Mock data used in the verification can be found in the `COVIDcorr` R package, available at https://github.com/CoVPN/correlates_mockdata. Any use of this code outside of the mock data is not guaranteed and is subject to additional verification.

### Verification Assignments

The verification results will be contained in `verification_results.pdf`, where the results of the independent verification will be reported. It will contain a table that lists the table generated, the original source code filename, the verification code filename, the results of the comparison, and the date the testing is completed.
