---
title: 'Verification Report: correlates_graphical'
author: "Di Lu"
date: "2021/03/27"
output:
  html_document: default
  pdf_document: default
---

## Description

This is the verification report for the `cor_graphical` folder of the `correlates_reporting` project for CoVPN. 

In the verification process, the output of `cor_graphical_verification_code.R` is compared against the plots listed in the the folder `immuno_graphical/verification/verification_input`. The values presented in the original plot against the ones generated by the verification code. Any statistical calculations will either be verified by computing them to a verified statistical table , or they will be generated independently.

The files `cor_graphical/verification/verification_input/practice_data.csv`, `cor_graphical/verification/verification_input/longer_cor_data_plot1.rds` and 
`cor_graphical/verification/verification_input/plot.25sample1.rds` was provided by the original programmer to the tester for verification purposes.

####lineplots of Binding Antibody to Spike: baseline negative vaccine arm (2 timepoints)
Outputs of Line plots, Violin plots and box plots and were visually compared to the outputs generated by primary programmer, one issue that was identified was the titer values were turncated by wrong ULOQ, so the verification is pending.

####lineplots of Pseudovirus Neutralization ID50: baseline negative vaccine arm (2 timepoints)
Outputs of Line plots, Violin plots and box plots and were visually compared to the outputs generated by primary programmer, and passes the verification.

####lineplots of Binding Antibody to Spike: baseline negative vaccine arm (3 timepoints)
Outputs of Line plots, Violin plots and box plots and were visually compared to the outputs generated by primary programmer, and passes the verification.


```{r echo = FALSE, message = FALSE, tidy = FALSE, cache = FALSE, results = 'asis'}
suppressWarnings({
suppressPackageStartupMessages({
library(knitr)
library(kableExtra)
library(tibble)
})})
options(kableExtra.latex.load_packages = FALSE, 
        knitr.table.format = "latex",
        knitr.kable.NA = '',
        width = 40,
        usethis.quiet = TRUE)
signature_table <- function(people){
  # check that the tables have correct variables
  if (!all(c("role", "name") %in% tolower(names(people)))) {
    stop(paste0("people table must have variables: role and name. ",
                "Contains: ", paste0(tolower(names(people)), collapse = ", ")))
  }
  
  people$signature <- NA
  people$date <- NA
  names(people) <- tolower(names(people))
  people[, c("role", "name", "signature", "date")] %>% 
  kable(col.names = c("Role", "Name", "Signature", "Date"),
        escape = FALSE, booktabs = FALSE) %>% 
    kable_styling(full_width = FALSE, position = "left") %>% 
    row_spec(0, background = rgb(184, 204, 228, maxColorValue = 255)) %>% 
    column_spec(1, width = "9em", border_left = TRUE) %>% 
    column_spec(2, width = "11em") %>% 
    column_spec(3, width = "15em") %>% 
    column_spec(4, width = "8em", border_right = TRUE)
}
tibble::tribble(
  ~ name,                ~ role,
  "Di Lu",  "Tester"
) %>% 
  signature_table()
```
