---
title: Verification Plan for Correlates of Risk Plots
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

Project directory: `correlates_reporting/cor_graphical`

Specifications: `correlates_reporting/cor_graphical/verification/cor_graphi_specifications.md`

Other Background Information: N/A 

### Verification  Sign-Off

```{r signatures, echo = FALSE, message = FALSE, tidy = FALSE, cache = FALSE, results = 'asis'}
library(knitr)
library(kableExtra)
library(tibble)

options(kableExtra.latex.load_packages = FALSE, 
        knitr.table.format = "latex",
        knitr.kable.NA = '',
        width = 40,
        usethis.quiet = TRUE)

signature_table <- function(people){
  # check that the tables have correct variables
  if (!all(c("role", "name") %in% tolower(names(people)))) {
    stop(paste0("people table must have variables: role and name. ",
                "Contains: ", paste0(tolower(names(people)), collapse = ", ")))
  }
  
  people$signature <- NA
  people$date <- NA
  names(people) <- tolower(names(people))
  people[, c("role", "name", "signature", "date")] %>% 
  kable(col.names = c("Role", "Name", "Signature", "Date"),
        escape = FALSE, booktabs = FALSE) %>% 
    kable_styling(full_width = FALSE, position = "left") %>% 
    row_spec(0, background = rgb(184, 204, 228, maxColorValue = 255)) %>% 
    column_spec(1, width = "9em", border_left = TRUE) %>% 
    column_spec(2, width = "11em") %>% 
    column_spec(3, width = "15em") %>% 
    column_spec(4, width = "8em", border_right = TRUE)
}

tibble::tribble(
  ~ name,                ~ role,
  "Dr. Peter Gilbert",  "Manager",
  "Dr. David Benkeser", "Programmer",
  "Nima Hejazi",        "Programmer",
  "Yiwen Lu",           "Specifier/Programmer",
  "Kendric Li",         "Programmer",
  "Di Lu",                   "Tester" 
) %>% 
  signature_table()

```

## Verification Procedure

Verification for the correlates of risk plots generated in support of the CoVPN correlates reporting will be based on a risked based approach. Risk of a plot is determined by importance: whether it will be used to drive decision making. Plots that are determined to have high importance, thus high risk, will go through independent double programming. If a plot is decided to have low risk, it will be verified via code review, not through independent double programming. A plot will be verified by someone other than the original programmer (the tester). 

For independent double programming, the tester will independently generate the same the data set based on the plots specification. For verification the tester will use the following procedure: First, the tester will programmatically compare the data set they generate for a plot against the one generated by the original programmer to confirm they contain the same values. Next, any statistical values shown in the plots will be calculated by the tester and verified against what the original programmer calculated programmatically. Finally, the tester will visually compare their generated data to visually inspect and compare against the original plot generated by the original programmer. The tester will document the results of each comparison in a results pdf for sign off.

For code review, the tester will review the programmers code directly from the code folder. The review will consist of checking the programming logic of the code for consistency with the specifications, verifying the assumptions in the source data. The tester will confirm that the code does not produce errors or unexpected warnings, check the output for nonsensical or unexpected results, and finally review the output headers, footers and formatting for consistency.

The plots targeted for independent double programming include:

  - Fig 1.3; RCDF plots for D57 Ab markers: baseline negative by treatment arm and D57 case/non-case.
  - Fig 1.6; Boxplots of D57 Ab markers: baseline negative vaccine arm by cases and non-cases
  - Fig 1.14; lineplots of Binding Antibody to Spike: baseline negative vaccine arm (2 timepoints)
  - Fig 1.18; lineplots of Pseudovirus Neutralization ID50: baseline negative vaccine arm (2 timepoints)
  - Fig 1.30; lineplots of Binding Antibody to Spike: baseline negative vaccine arm (3 timepoints)

Mock data used in the verification can be found in the `COVIDcorr` R package, available at https://github.com/CoVPN/correlates_mockdata. Any use of this code outside of the mock data is not guaranteed and is subject to additional verification.

### Verification Assignments

The verification results will be contained in `verification_results.pdf`, where the results of the independent verification will be reported. It will contain a table that lists the Plot, the original source code filename, the verification code filename, the results of the visual comparison, and the date the testing is completed.


