---
knit: "bookdown::render_book"
title: "COVID-19 Correlates of Protection Analysis Report"
subtitle: '`r source(here::here("_common.R")); paste(study_name, "Study")`'
author: "USG COVID-19 Response Biostatistics Team"
date: "`r format(Sys.time(), '%B %d, %Y')`"
documentclass: book
site: bookdown::bookdown_site
bibliography: [book.bib, packages.bib]
biblio-style: apalike
suppress-bibliography: true
link-citations: yes
colorlinks: yes
graphics: yes
lot: yes
lof: yes
always_allow_html: yes
header-includes:
   - \usepackage{eso-pic,graphicx,transparent,caption,pdflscape,float,titling} # keep titling last!
   - \usepackage[margin=1in]{geometry}
---

```{r, include = knitr::is_latex_output() & startsWith(study_name, "Mock")}
knitr::asis_output("\\AddToShipoutPictureFG{
  \\AtPageCenter{
    \\makebox[0pt]{\\rotatebox[origin=c]{45}{
      \\scalebox{10}{\\texttransparent{0.3}{MOCK}}}}}}")
```


`r if ( !( grepl("moderna", attr(config::get(config = Sys.getenv("TRIAL")), "config") ) ) )'<!--'`

# Disclaimers

* The data presented in the analysis originated from the Moderna Sponsored mRNA-1273-P301 clinical study and are provided to NIAID in accordance with Clinical Trial Agreement between the parties. The study was funded in part by BARDA under Government Contract No. 75A50120C00034

* The preliminary immunogenicity data presented here do not reflect the Sponsors statistical analysis plan and therefore should not be interpreted as a protocol defined read-out of the clinical study.

* These data are not to be disclosed without written permission of Moderna.


`r if ( !( grepl("moderna", attr(config::get(config = Sys.getenv("TRIAL")), "config") ) ) ) '-->'`


`r if (knitr::is_latex_output()) '<!--'`

# CoVPN Correlates Analysis Report {-}

## Statistical Analysis Plan {-}

The SAP is available at https://doi.org/10.6084/m9.figshare.13198595

## Reproducibility Notice {-}

This project integrates the virtual environments framework provided by [the
`renv` package](https://rstudio.github.io/renv/) for computational
reproducibility. By taking this approach, all results are generated using a
consistent versioning of both R and several R packages. This version of the
report was built with `r R.version.string`, [pandoc](https://pandoc.org/)
version `r rmarkdown::pandoc_version()`, and the following R packages:

```{r pkg-list, echo=FALSE, results="asis"}
# borrowed from https://github.com/tidymodels/TMwR/blob/master/index.Rmd
deps <- desc::desc_get_deps()
pkgs <- sort(deps$package[deps$type == "Imports"])
pkgs <- sessioninfo::package_info(pkgs, dependencies = FALSE)
df <- tibble::tibble(
  package = pkgs$package,
  version = pkgs$ondiskversion,
  source = gsub("@", "\\\\@", pkgs$source)
)
knitr::kable(df, format = "markdown")
```

To get started with using this project and its `renv` package library, we
first recommend briefly reviewing the [`renv` collaboration
guide](https://rstudio.github.io/renv/articles/collaborating.html).

`r if (knitr::is_latex_output()) '-->'`
