#!/bin/bash

for T in moderna_mock janssen_pooled_mock # janssen_pooled_real  janssen_pooled_mock  janssen_na_mock
do
	export TRIAL=$T	
	echo $TRIAL
	if [[ "$1" == "cor_coxph" ]] 
	then
		make -k -C $1 cor_coxph # save some time
	else
		make -k -C $1 all
	fi
	if [[ "$1" == "base_riskscore" ]] 
	then
		bash ./_build.sh riskscore
	else
		bash ./_build_chapter.sh $1
	fi
done
