---
title: 'Verification Report: immuno_graphical'
author: "Di Lu"
date: "2021/03/27"
output:
  html_document: default
  pdf_document: default
---

## Description

This is the verification report for the `immuno_graphical` folder of the `correlates_reporting` project for CoVPN. 

In the verification process, the output of `immuno_graphical_verification_code.R` is compared against the plots listed in the the file `immuno_graphical/verification/verification_plan.pdf`. The values presented in the original plot against the ones generated by the verification code. Any statistical calculations will either be verified by computing them to a verified statistical table , or they will be generated independently.

The files `immuno_graphical/verification/verification_input/practice_data.csv`, `immuno_graphical/verification/twophase_data.csv` and 
`immuno_graphical/verification/long_twophase_data.csv` was provided by the original programmer to the tester for verification purposes.

####Pair plots of D57 Ab markers: baseline negative vaccine arm
Output of Scatter plots, density plots and partial partial Spearman's correlation are equivalent to the output generated by primary programmer, so passes the verification.

####RCDF plots for D57 Ab markers: by baseline status for the vaccine arm.
Key statistics(0th, 10th, 20th, 30th, 40th, 50th, 60th, 70th, 80th, 90th, 100th percentile) of the RCDF and RCDF curve itself are equivalent to the output generated by primary programmer, so passes the verification.

####Boxplots of D57 Ab markers: baseline negative vaccine + placebo arms
Key statistics(min, 25th percentile, median, mean, 75th percentile, max) of marker values are equivalent to the output generated by primary programmer, so passes the verification.

####Spaghetti plots of Ab markers over time: baseline negative vaccine + placebo arm
Key statistics(min, 25th percentile, median, mean, 75th percentile, max) of marker values are equivalent to the output generated by primary programmer, so passes the verification.

## Signatures

```{r echo = FALSE, message = FALSE, tidy = FALSE, cache = FALSE, results = 'asis'}
suppressWarnings({
suppressPackageStartupMessages({
library(knitr)
library(kableExtra)
library(tibble)
})})
options(kableExtra.latex.load_packages = FALSE, 
        knitr.table.format = "latex",
        knitr.kable.NA = '',
        width = 40,
        usethis.quiet = TRUE)
signature_table <- function(people){
  # check that the tables have correct variables
  if (!all(c("role", "name") %in% tolower(names(people)))) {
    stop(paste0("people table must have variables: role and name. ",
                "Contains: ", paste0(tolower(names(people)), collapse = ", ")))
  }
  
  people$signature <- NA
  people$date <- NA
  names(people) <- tolower(names(people))
  people[, c("role", "name", "signature", "date")] %>% 
  kable(col.names = c("Role", "Name", "Signature", "Date"),
        escape = FALSE, booktabs = FALSE) %>% 
    kable_styling(full_width = FALSE, position = "left") %>% 
    row_spec(0, background = rgb(184, 204, 228, maxColorValue = 255)) %>% 
    column_spec(1, width = "9em", border_left = TRUE) %>% 
    column_spec(2, width = "11em") %>% 
    column_spec(3, width = "15em") %>% 
    column_spec(4, width = "8em", border_right = TRUE)
}
tibble::tribble(
  ~ name,                ~ role,
  "Di Lu",  "Tester"
) %>% 
  signature_table()
```