# Specifications for DAT_CLEAN 

Different TRIAL variable values go through different logical paths of this script and will be tested separately. For now, we have \begin{itemize}
  \item moderna_mock
  \item ensemble_mock
\end{itemize}
There is no need to test has29 or not anymore.


Steps:
\begin{itemize}

  \item Rename the first column to Ptid
  
  \item Subset to not missing in Bserostatus
  
  \item Subset to rows not missing in EventTimePrimaryD1 and not missing in EventTimePrimaryD29
  
  \item If has57 (defined in _common.R), subset to rows not missing in EventTimePrimaryD57
  
  \item Define EarlyendpointD29 as: EarlyinfectionD29==1 | (EventIndPrimaryD1==1 & EventTimePrimaryD1 < NumberdaysD1toD29 + 7),1,0))

  \item If has57, Define EarlyendpointD57 as: EarlyinfectionD57==1 | (EventIndPrimaryD1==1 & EventTimePrimaryD1 < NumberdaysD1toD57 + 7),1,0))

  \item Define age.geq.65, a binary variable indicating Age >= 65

  \item Define Senior, 1 if Age >= 65 (moderna) or Age >= 60 (janssen)

  \item Define ethnicity, a factor variable that has three levels:   "Hispanic or Latino", "Not Hispanic or Latino", "Not reported and unknown"

  \item Define race, a factor variable that has the following levels:   "White", "Black or African American",
  "Asian", "American Indian or Alaska Native", if (ENSEMBLE) "Indigenous South American"
  "Native Hawaiian or Other Pacific Islander", "Multiracial",
  if (COVE) "Other", "Not reported and unknown"

  \item Define WhiteNonHispanic, a binary variable that takes value 1 if race is White and ethnicity is not Hispanic, 0 if race is not "white or unknown" OR ethnicity is Hispanic, and NA otherwise
  
  \item Define MinorityInd, a binary variable that takes value 1 if WhiteNonHispanic is 0, and 0 otherwise including when WhiteNonHispanic is NA. For Janssen, set MinorityInd to 0 for region 1 and 2
  
  \item Define Bstratum, an integer variable to index strata defined by age and at risk. For Moderna, there are three strata: age >= 65, age < 65 and HighRiskInd==1, age < 65 and HighRiskInd==0. For Janssen, there are four strata, from 1 to 4: age < 60 and HighRiskInd==0, age < 60 and HighRiskInd==1, age >= 60 and HighRiskInd==0, and age >= 60 and HighRiskInd==1.
  
  \item Define demo.stratum, an integer variable to index the demographics strata. For Moderna, there are 6 strata: URMforsubcohortsampling [1, 0] x Bstratum. For Janssen, there are 16 strata: US/URM, US/nonURM, Latin America, and South Africa. Note that there are NA's in URMforsubcohortsampling, so demo.stratum and variables that depend on it would have NA's as well.
  
  \item Define tps.stratum, an integer variable to index correlates sampling strata. For Moderna and Janssen, there are 24 and 64 strata, respectively: [placebo/baseline negative, placebo/baseline positive, vaccine/baseline negative, vaccine/baseline positive] x demo.stratum

  \item Define Wstratum, an integer variable to index strata for computing weights. For Moderna and Janssen, there are 28 strata and 68 strata, respectively. Compared to tps.stratum, the four additional strata are the cases (based off EventIndPrimaryD29) in placebo/baseline negative, placebo/baseline positive, vaccine/baseline negative, and vaccine/baseline positive, respectively. Notes: a) Some strata may be empty. b) A case will be assigned one of the new stratums even if its demo.stratum is NA as all cases will have trt and Bserostatus. 
  
  \item If has57, define TwophasesampIndD57, a 0/1 variable. It is defined as as the intersection of
  \begin{itemize}
    \item either in the subchort or EventIndPrimaryD29 == 1
    \item no missing values in baseline, Day 29, or Day 57 binding to Spike or RBD
  \end{itemize}  

  \item If has29, define TwophasesampIndD29, a 0/1 variable. It is defined as as the intersection of
  \begin{itemize}
    \item either in the subchort or EventIndPrimaryD29 == 1
    \item no missing values in baseline or Day 29 binding to Spike or RBD
  \end{itemize}  

  \item If has57, define wt.D57. The weights equal the sampling probabilities of TwophasesampIndD57==1 within each Wstratum. This variable is only defined for subjects satisfying EarlyendpointD57==0 & Perprotocol == 1 & EventTimePrimaryD57>=7 and set to NA otherwise. Define ph1.D57 as having non-NA wt.D57. Define ph2.D57 as ph1.D57 & TwophasesampIndD57.
  
  \item Repeat above for 29.
  
  \item If has57 and has29, define wt.intercurrent.cases. The weights equal the sampling probabilities of TwophasesampIndD29==1 within each Wstratum. This variable is only defined for subjects satisfying EarlyendpointD29==0 & Perprotocol==1 & EventIndPrimaryD29==1 & EventTimePrimaryD29>=7 & EventTimePrimaryD29 <= 6 + NumberdaysD1toD57 - NumberdaysD1toD29 and set to NA otherwise. Define ph1.intercurrent.cases. as having non-NA wt.intercurrent.cases. Define ph2.intercurrent.cases as ph1.D57 & TwophasesampIndD29.
  
  \item Define wt.subcohort. For Moderna, the weights equal the sampling probabilities of TwophasesampIndD57==1 & SubcohortInd within each tps.stratum. This variable is only defined for subjects satisfying EarlyendpointD57==0 & Perprotocol == 1 and set to NA otherwise. Define ph1.immuno as having non-NA wt.subcohort. ph2.immuno as ph1.immuno & SubcohortInd & TwophasesampIndD57. For Janssen, change 57 to 29. 
  
  \item If has57, carry out single imputation using the `R` package `mice` for the subjects satisfying TwophasesampIndD57==1. Imputation is done separately for vaccine arm baseline seronegative, vaccine arm baseline seropositive, placebo arm baseline seronegative, and placebo arm baseline seropositive. Since baseline, D29 and D57 binding to Spike and RBD are required in this subset of people, the imputation is intended to fill in missing marker values for neutralization assays at these three time points. The imputation is done with the package mice with default parameters and seed 1. Notes: 1. The order of variables matters in imputation: c(outer(c("B", "Day29", "Day57"), c("bindSpike", "bindRBD", "pseudoneutid50", "pseudoneutid80"), "%.%")). 2. If there is no missing data in the dataset, this piece cannot be verified. 3. Be careful not to change subjects outside TwophasesampIndD57==1. 4. diagnostics = FALSE and remove_collinear=F are needed in call to mice to avoid errors due to collinearity. 5. Before imputation, check to see if any columns are constant columns with missing values. If yes, set the whole column to the constant, including the missing values, otherwise mice will throw an error.

  \item Repeat single imputation for the subjects satisfying TwophasesampIndD29==1 and only impute these variables: c(outer(c("B", "Day29"), c("bindSpike", "bindRBD", "pseudoneutid50", "pseudoneutid80"), "%.%")).  


  \item Apply conversion factors (defined in _common.R) to all the binding and ID50 and ID80 variables at baseline, Day29 and Day57. No need to apply conversion factors to deltas because they are fold changes and the conversion factors cancel out. Note that conversion factor is on antilog scale.
  
  \item Censor each of the markers in all markers (including bindN but not liveneutmn50 yet) measured by baseline, Day29 and Day57. Censoring means setting values < lower limits of detection (llods, defined in _common.R) to half of the llods. (Note that llods are on the antilog scale and need to be transformed.) However, we will not set values > uloqs to uloqs for either binding variables or nAb markers. ULOQ censoring may happen in sub-analyses.
  
  \item Define Delta57overBxxx (if has57), Delta29overBxxx (if has29), and Delta57over29xxx (if has57 and has29) for each xxx in the variable assays+bindN. This step needs to happen after censoring. Deltas are computed by taking the difference between two markers. Since the markers are on the log scale, the deltas represent the log10 fold rise. No transformation is needed. Negative values are left as they are. One complication here is that we want to censor by lloqs (set values less than lloqs to half of lloqs) before computing the delta, but we want the individual time points markers to remain censored by lloq.
  
  \item Finally, if subset_value != "All" (defined in _common.R through config), subset to subset_variable==subset_value.

}

  

\end{itemize}



