---
title: Verification Plan for Shared Data Cleaning
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

Project directory: `correlates_reporting/data_clean`

Specifications: `correlates_reporting/data_clean/verification/dat_clean_specifications.pdf`

Other Background Information: N/A 

### Verification  Sign-Off

```{r signatures, echo = FALSE, message = FALSE, tidy = FALSE, cache = FALSE, results = 'asis'}
library(knitr)
library(kableExtra)
library(tibble)

options(kableExtra.latex.load_packages = FALSE, 
        knitr.table.format = "latex",
        knitr.kable.NA = '',
        width = 40,
        usethis.quiet = TRUE)

signature_table <- function(people){
  # check that the tables have correct variables
  if (!all(c("role", "name") %in% tolower(names(people)))) {
    stop(paste0("people table must have variables: role and name. ",
                "Contains: ", paste0(tolower(names(people)), collapse = ", ")))
  }
  
  people$signature <- NA
  people$date <- NA
  names(people) <- tolower(names(people))
  people[, c("role", "name", "signature", "date")] %>% 
  kable(col.names = c("Role", "Name", "Signature", "Date"),
        escape = FALSE, booktabs = FALSE) %>% 
    kable_styling(full_width = FALSE, position = "left") %>% 
    row_spec(0, background = rgb(184, 204, 228, maxColorValue = 255)) %>% 
    column_spec(1, width = "9em", border_left = TRUE) %>% 
    column_spec(2, width = "11em") %>% 
    column_spec(3, width = "15em") %>% 
    column_spec(4, width = "8em", border_right = TRUE)
}

tibble::tribble(
  ~ name,                ~ role,
  "Dr. Peter Gilbert",  "Manager",
  "Dr. Youyi Fong",     "Specifier/Programmer",
  "Dr. David Benkeser", "Programmer",
  "Nima Hejazi",        "Programmer",
  "Ellis Hughes",       "Tester" 
) %>% 
  signature_table()

```

## Verification Procedure

Verification for the shared cleaned data generated in support of the CoVPN correlates reporting will be based on a risked based approach. Risk of this data is high as it is shared across all the report elements. As such, it will go through independent double programming for verification. The data output will be verified by someone other than the original programmer (the tester). 

For independent double programming, the tester will independently generate the same the data set based on the specifications. For verification the tester will programmatically compare the all the data generated against the data generated by the original programmer to confirm they contain the same values. The tester will document the results of the comparison in a results pdf for sign off.

Mock data used in the verification can be found in the `data_raw` folder of this repository, available at https://github.com/CoVPN/correlates_reporting. Any use of this code outside of the mock data is not guaranteed and is subject to additional verification.

### Verification Assignments

The verification results will be contained in `verification_results.pdf`, where the results of the independent verification will be reported. It will contain a table that lists the Plot, the original source code filename, the verification code filename, the results of the visual comparison, and the date the testing is completed.


