---
title: "CoVPN COVID-19 Vaccine Efficacy Trial CoR Report - Verification"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
  pdf_document:
    df_print: kable
    toc: yes
    toc_depth: 2
classoption: landscape
header-includes: \usepackage{caption}
---
  
```{r setup, include=FALSE, echo=FALSE}
library(tidyverse)
library(Hmisc)
library(survey)
library(rlang)
options(scipen=999) # Turn off scientific notation
options(survey.lonely.psu="adjust") 
renv::activate(project = here::here(".."))
source(here::here("..", "_common.R"))

```

```{r dataio, echo=FALSE}

# read in practice data
dat.mock <- read.csv(here("verification","verification_input","practice_data.csv"), stringsAsFactors = F)
dat <- dat.mock

dat$immuno_ind <- with(dat, ifelse(Perprotocol==1 & SubcohortInd==1 & TwophasesampIndD57==1 & EarlyendpointD57==0 & !is.na(wt.subcohort), 1, 0))

# assign values above the uloq to the uloq
for (a in c("bindN","bindSpike","bindRBD","pseudoneutid50","pseudoneutid80")) {
  for (t in c("B", "Day29", "Day57") ) {
    dat[[t %.% a]] <- ifelse(dat[[t %.% a]] > log10(uloqs[a]), log10(uloqs[a]), dat[[t %.% a]])
  }
}

# reset Delta over Baseline: Delta are based on values < LLOQ set to LLOQ/2 and > ULOQ set to ULOQ
for (a in c("bindN","bindSpike","bindRBD","pseudoneutid50","pseudoneutid80")) {
  dat[["Delta57overB" %.% a]] <- dat[["Day57" %.% a]] - dat[["B" %.% a]]
  dat[["Delta29overB" %.% a]] <- dat[["Day29" %.% a]] - dat[["B" %.% a]]
}

# wide to long by marker and timepoint
dat.long <- dat %>%
  pivot_longer(colnames(dat)[grepl("bindN|bindRBD|bindSpike|pseudoneut|liveneutmn", colnames(dat))], names_to = "time_marker", values_to = "readout_trunc") %>% filter(!grepl("CPV", time_marker)) %>%
  mutate(time = gsub("bindN|bindRBD|bindSpike|pseudoneutid.*|liveneutmn.*", "", time_marker),
         marker = gsub("^B|^Day29|^Day57|^29|^57", "", gsub("Delta29over|Delta57over", "", time_marker)))


# define subgroups: age, risk, age & risk, sex, EthnicityHispanic, race, minority, age & minority etc
dat.long <- dat.long %>%
  mutate(Age65C = ifelse(age.geq.65 == 1, "Age >= 65", "Age < 65"),
         HighRiskC = ifelse(HighRiskInd == 1, "At-risk", "Not at-risk"),
         SexC = ifelse(Sex == 1, "Female", "Male"),
         EthHisC = ifelse(EthnicityHispanic==1, "Hispanic or Latino",
                          ifelse(EthnicityHispanic==0 & EthnicityNotreported==0 & EthnicityUnknown==0, "Not Hispanic or Latino",
                                 ifelse(EthnicityNotreported==1 | EthnicityUnknown==1, "Not reported and unknown ", NA))),
         RaceEthC = as.character(race),
         MinorityC = ifelse(WhiteNonHispanic == 0, "Communities of Color",
                            ifelse(WhiteNonHispanic == 1, "White Non-Hispanic", NA)),
         AgeRiskC = paste(Age65C, HighRiskC),
         AgeSexC = paste(Age65C, SexC),
         AgeMinorC = ifelse(!is.na(MinorityC), paste(Age65C, MinorityC), NA)
  )

# create a new RaceEthC including white hispanic for demographic table reporting
dat.long$RaceEthC2=dat.long$RaceEthC
#dat.long$RaceEthC2[which(dat.long$RaceEthC2 == 'White' & dat.long$WhiteNonHispanic == 1)] <- 'White Non-Hispanic '
# code white non-hispanic group and set white hispanic as NA
dat.long$RaceEthC[which(dat.long$RaceEthC == 'White' & dat.long$WhiteNonHispanic == 1)] <- 'White Non-Hispanic '
dat.long$RaceEthC[which(dat.long$RaceEthC == 'White')] <- NA

# define response variables
dat.long <- dat.long %>% 
  mutate(LLoQ = lloqs[as.character(marker)],
         pos.cutoffs = pos.cutoffs[as.character(marker)],
         bind_response_2LQ = ifelse(grepl("bind", marker) & readout_trunc>=log10(2*LLoQ) & !grepl("Delta",time), 1, ifelse(grepl("bind", marker) & readout_trunc<log10(2*LLoQ) & !grepl("Delta",time), 0, NA)),
         bind_response_4LQ = ifelse(grepl("bind", marker) & readout_trunc>=log10(4*LLoQ) & !grepl("Delta",time), 1, ifelse(grepl("bind", marker) & readout_trunc<log10(4*LLoQ) & !grepl("Delta",time), 0, NA)),
         
         baseline_lt_thres = ifelse(time=="B" & readout_trunc >= log10(LLoQ), 1, 0),
         increase_4F_D29 = ifelse(time=="Delta29overB" & readout_trunc>log10(4), 1, 0),
         increase_4F_D57 = ifelse(time=="Delta57overB" & readout_trunc>log10(4), 1, 0),
         
         response_2FR = ifelse(grepl("Delta",time) & readout_trunc>=log10(2), 1, 
                               ifelse(grepl("Delta",time) & readout_trunc<log10(2), 0, NA)),
         response_4FR = ifelse(grepl("Delta",time) & readout_trunc>=log10(4), 1, 
                               ifelse(grepl("Delta",time) & readout_trunc<log10(4), 0, NA))
  ) %>%
  group_by(Ptid, marker) %>%
  mutate(baseline_lt_thres_ptid=max(baseline_lt_thres),
         increase_4F_D29_ptid=max(increase_4F_D29),
         increase_4F_D57_ptid=max(increase_4F_D57)) %>%
  ungroup() %>%
  mutate(response_nab = ifelse(time %in% c("B","Day29","Day57") & baseline_lt_thres_ptid == 0 & readout_trunc > log10(LLoQ), 1,
                           ifelse(baseline_lt_thres_ptid == 1 & time == "B", 1, 
                                  ifelse(baseline_lt_thres_ptid == 1 & time == "Day29" & increase_4F_D29_ptid==1, 1, 
                                         ifelse(baseline_lt_thres_ptid == 1 & time == "Day57" & increase_4F_D57_ptid==1, 1,
                                                ifelse(time %in% c("B","Day29","Day57"), 0, NA))))),
         response_bind = ifelse(readout_trunc > log10(pos.cutoffs), 1, 0),
         response = ifelse(marker %in% c("bindSpike","bindRBD","bindN"), response_bind, 
                           ifelse(marker %in% c("pseudoneutid50","pseudoneutid80","liveneutmn50"), response_nab, NA))
         )


# label Trt, Bserostatus, time and marker
dat.long <- dat.long %>% 
  mutate(Trt_lb = ifelse(Trt == 0, "Placebo", "Vaccine"),
         Baseline = ifelse(Bserostatus == 0, "Negative","Positive"),
         Visit = ifelse(time == "B", "Day 1", 
                        ifelse(time=="Day29", "Day 29", 
                               ifelse(time=="Day57","Day 57", 
                                      ifelse(time=="Delta29overB","D29 fold-rise over D1",
                                             ifelse(time=="Delta57over29","D57 fold-rise over D29",
                                                    ifelse(time=="Delta57overB","D57 fold-rise over D1", NA)))))),
         Marker = ifelse(marker=="bindSpike","Anti Spike IgG (IU/ml)",
                         ifelse(marker=="bindRBD","Anti RBD IgG (IU/ml)", 
                                ifelse(marker=="bindN","Anti N IgG (IU/ml)",
                                       ifelse(marker=="pseudoneutid50","Pseudovirus-nAb ID50",
                                              ifelse(marker=="pseudoneutid80","Pseudovirus-nAb ID80",
                                                     ifelse(marker=="liveneutmn50","Live virus-nAb MN50", NA)))))))


# parameters set-up
tbl_num <- 1
groupby_vars=c("VarName","Group","Baseline", "Trt_lb", "Marker", "Visit")
two_timepoints=c("Day 29","Day 57")
three_timepoints=c("Day 1","Day 29","Day 57")

## functions
decimal_f <- function(x, d) { # rounding values
  trimws(format(round(x, d), nsmall=d))
}

# load all immuno tabs from Chenchen
load(here("verification","verification_input","Tables_cor.Rdata"), verbose=T)
```

\captionsetup[table]{labelformat=empty}

\clearpage

## Table. Demographic 
```{r tab_dm, results = "asis", echo=FALSE, message=FALSE}
for (i in c("Negative", "Positive")){
  
  demo <- subset(dat.long, Baseline==i) %>% filter(immuno_ind==1) %>%
    select(Trt_lb, Ptid, Age65C, HighRiskC, SexC, EthHisC, RaceEthC2, MinorityC, AgeRiskC) %>% 
    mutate(MinorityC = ifelse(is.na(MinorityC), "NA", MinorityC)) %>%
    unique() %>% 
    mutate(AgeRiskC=ifelse(grepl("Age >= 65", AgeRiskC), "Age >= 65 ", AgeRiskC))
  
  
  demo.long <- demo %>%
    pivot_longer(!c(Trt_lb, Ptid), names_to = "VarName", values_to="Group")
    
  
  tab_dm_by_trt <- demo.long %>% 
    group_by(Trt_lb, VarName, Group) %>% 
    filter(!is.na(Group)) %>%
    summarise(N=n()) %>% 
    mutate(n_freq = paste0(N, " (", decimal_f( N / sum(N) * 100, 1),"%)")) %>% 
    select(-N) %>%
    pivot_wider(names_from = "Trt_lb", values_from = "n_freq") %>% 
    bind_rows(
      subset(dat, Bserostatus==ifelse(i=="Negative",0, 1) & immuno_ind==1) %>% mutate(Trt_lb = ifelse(Trt==0, "Placebo", "Vaccine")) %>%
        group_by(Trt_lb) %>% 
        summarise(age=paste0(decimal_f(mean(Age),1), " (", decimal_f(min(Age),1),", ",decimal_f(max(Age),1),")")) %>%
        pivot_wider(names_from = "Trt_lb", values_from="age") %>%
        mutate(VarName="Age65C",
               Group="Mean (Range)")
    ) %>%
    bind_rows(
      subset(dat, Bserostatus==ifelse(i=="Negative",0, 1) & immuno_ind==1) %>% mutate(Trt_lb = ifelse(Trt==0, "Placebo", "Vaccine")) %>%
        group_by(Trt_lb) %>% 
        summarise(BMI=paste0(decimal_f(mean(BMI),1), " +/- ", decimal_f(sd(BMI),1))) %>%
        pivot_wider(names_from = "Trt_lb", values_from="BMI") %>%
        mutate(VarName="BMI",
               Group="Mean +/- SD")
    )
  
  tab_dm_tot<- demo.long %>% 
    group_by(VarName, Group) %>% 
    filter(!is.na(Group)) %>%
    summarise(N=n()) %>% 
    mutate(Total = paste0(N, " (", decimal_f( N / sum(N) * 100, 1),"%)")) %>% 
    select(-N) %>%
    bind_rows(
      subset(dat, Bserostatus==ifelse(i=="Negative",0, 1) & immuno_ind==1) %>% 
        summarise(Total=paste0(decimal_f(mean(Age),1), " (", decimal_f(min(Age),1),", ",decimal_f(max(Age),1),")")) %>%
        mutate(VarName="Age65C",
               Group="Mean (Range)")
    ) %>%
    bind_rows(
      subset(dat, Bserostatus==ifelse(i=="Negative",0, 1) & immuno_ind==1) %>% 
        summarise(Total=paste0(decimal_f(mean(BMI),1), " +/- ", decimal_f(sd(BMI),1))) %>%
        mutate(VarName="BMI",
               Group="Mean +/- SD")
    )
  
  
  tab_dm <- tab_dm_by_trt %>%
    left_join(tab_dm_tot,  by=c("VarName","Group")) %>%
    filter(!is.na(Group)) %>%
    mutate(VarName=gsub("AgeRisk","Age, Risk for Severe Covid-19", gsub("HighRisk","Risk for Severe Covid-19", gsub("His","Hispanic or Latino ethnicity", gsub("EthC2|Eth|65|C", "", VarName))))) %>%
    mutate(VarName=ifelse(VarName=="Minority", "Race", VarName)) %>%
    select(VarName, Group, Placebo, Vaccine, Total)
  
  
  count <- demo %>% group_by(Trt_lb) %>%  summarise(N=n())
  
  colnames(tab_dm) = c("subgroup", "Characteristics", paste0(count$Trt_lb,"\n(N = ",count$N,")"), paste0("Total\n(N = ", sum(count$N),")"))
  
  tab_dm <- tab_dm %>% select(1,2,4,3,5)

  if (i=="Negative"){
    # comparison
    tab_dm_neg[] <- lapply(tab_dm_neg, as.character)
    tab_dm_neg_v = tab_dm_neg[, c("subgroup","Characteristics")] %>% left_join(tab_dm, by=c("subgroup","Characteristics"))
    testthat::expect_equal(tab_dm_neg_v, tab_dm_neg)
    
  } else if (i=="Positive"){
    # comparison
    tab_dm_pos[] <- lapply(tab_dm_pos, as.character)
    tab_dm_pos_v = tab_dm_pos[, c("subgroup","Characteristics")] %>% left_join(tab_dm, by=c("subgroup","Characteristics"))
    testthat::expect_equal(tab_dm_pos_v, tab_dm_pos)
  }

}

save(tab_dm_neg_v, file = here::here("verification", "verification_output", "cor_tab_dm_neg_v.Rdata"))
save(tab_dm_pos_v, file = here::here("verification", "verification_output", "cor_tab_dm_pos_v.Rdata"))
```

\clearpage

## Table. Per-protocol Cases and Non-Cases
```{r pp_cases_noncases, results = "asis", echo=FALSE}

tab_strtm_v <- dat %>%
  select(Ptid, demo.stratum, age.geq.65, HighRiskInd, Perprotocol, EarlyendpointD29, EarlyendpointD57, TwophasesampIndD29, TwophasesampIndD57, EventIndPrimaryD1, EventIndPrimaryD29, EventIndPrimaryD57, Bserostatus, Trt) %>%
  mutate(
    new_strata = case_when(!is.na(demo.stratum)~ demo.stratum, age.geq.65 == 1 ~ 7L, age.geq.65 == 0 & HighRiskInd == 1 ~ 8L, age.geq.65 == 0 & HighRiskInd == 0 ~ 9L),
    baseline = ifelse(Bserostatus == 1, "Positive", "Negative"),
    arm = ifelse(Trt == 1, "Vaccine", "Placebo")
  ) %>%
  mutate(
    case_flag_D29 = ifelse(Perprotocol==1 & EarlyendpointD29==0 & TwophasesampIndD29==1 & EventIndPrimaryD29==1, 1, 0),
    case_flag_D57 = ifelse(Perprotocol==1 & EarlyendpointD57==0 & TwophasesampIndD57==1 & EventIndPrimaryD57==1, 1, 0),
    control_flag = ifelse(Perprotocol==1 & EarlyendpointD57==0 & TwophasesampIndD57==1 & EventIndPrimaryD1==0, 1, 0)) %>%
  group_by(baseline, arm, new_strata) %>%
  summarise(case29 = as.character(sum(case_flag_D29)),
            case57 = as.character(sum(case_flag_D57)),
            control = as.character(sum(control_flag))) %>%
  ungroup()

colnames(tab_strtm_v) <- colnames(tab_strtm)
  
testthat::expect_equal(tab_strtm_v, tab_strtm)

save(tab_strtm_v, file = here::here("verification", "verification_output", "cor_tab_strtm_v.Rdata"))

```

## Table. Antibody level comparison of Cases vs Non-Cases by baseline COVID status and assigned arms at Day 57
```{r case_vaccplcb_posneg, results = "asis", echo=FALSE, message=FALSE}
options(survey.lonely.psu="adjust") 

# response rate
ind=1
rr3_rate_list=list()
for (mk in c("Anti N IgG (IU/ml)","Anti RBD IgG (IU/ml)","Anti Spike IgG (IU/ml)","Pseudovirus-nAb ID50","Pseudovirus-nAb ID80")){
  for (tp in two_timepoints){
    
  rr3 <- dat.long %>% filter(Marker == mk & Visit == tp)  
  
  ph1_var = ifelse(tp==two_timepoints[1], "ph1.D29", "ph1.D57")
  ph2_var = ifelse(tp==two_timepoints[1], "ph2.D29", "ph2.D57")
  wt_var = ifelse(tp==two_timepoints[1], "wt.D29", "wt.D57")
  
  # Subset the data to “phase 1 ptids” for the correlates
  rr3 <- rr3 %>% filter((!!sym(ph1_var))==1)

  # define case/non case flag based on the time point in the loop
  if (tp==two_timepoints[1]) {
    rr3 <- rr3 %>%
      mutate(case_flag = ifelse(Perprotocol==1 & EarlyendpointD29==0 & TwophasesampIndD29==1 & EventIndPrimaryD29==1, "Cases", ifelse(Perprotocol==1 & EarlyendpointD57==0 & TwophasesampIndD57==1 & EventIndPrimaryD1==0, "Non_cases_Control", NA)))
               
    } else if (tp==two_timepoints[2]){
      rr3 <- rr3 %>%
        mutate(case_flag = ifelse(Perprotocol==1 & EarlyendpointD57==0 & TwophasesampIndD57==1 & EventIndPrimaryD57==1, "Cases", ifelse(Perprotocol==1 & EarlyendpointD57==0 & TwophasesampIndD57==1 & EventIndPrimaryD1==0, "Non_cases_Control", NA)))
  }
         
  design <- twophase(id = list(~Ptid, ~ Ptid), strata = list(NULL, ~ Wstratum), weights = list(NULL, ~eval(as.name(wt_var))), method="simple", subset=~eval(as.name(ph2_var)), data = rr3)

  mod <- svyby(~response, ~Visit+case_flag+Marker+Baseline+Trt_lb, design, survey::svyciprop, ci=TRUE, vartype="ci", na.rm=T)
  
  rr3_rate <- rr3 %>% filter((!!sym(ph2_var))==1 & !is.na(response) & !is.na(case_flag)) %>%
    group_by_at(c("Visit", "Baseline","Trt_lb","case_flag","Marker")) %>%
    summarise(N=n(),
              `Responder_1`=paste0(round(sum(response * (!!sym(wt_var)), na.rm=T),1),"/",round(sum((!!sym(wt_var))),1))) %>%
    left_join(mod, by=c("Visit","Baseline","Trt_lb","case_flag","Marker")) %>%
    mutate(`Responder_2` = ifelse(!is.nan(ci_u), paste0(decimal_f(response*100,1),"%\n(", decimal_f(ci_l*100,1),"%, ", decimal_f(ci_u*100,1),"%)"), paste0(decimal_f(response*100,1),"%"))
    ) %>%
    mutate(rslt = paste0(`Responder_1`, " = ", `Responder_2`)) %>%
    select(Visit, Baseline,Trt_lb, case_flag, Marker, N, rslt) %>%
    pivot_wider(names_from=case_flag,values_from=c(N, rslt))
  
  rr3_rate_list[[ind]] <- rr3_rate
  
  ind=ind+1
  }
}
rr3_rate_all <- do.call("rbind", rr3_rate_list)

# mag
ind=1
rr3_mag_list=list()
for (mk in c("Anti N IgG (IU/ml)","Anti RBD IgG (IU/ml)","Anti Spike IgG (IU/ml)","Pseudovirus-nAb ID50","Pseudovirus-nAb ID80")){
  for (tp in two_timepoints){
  
  rr3 <- dat.long %>% filter(Marker == mk & Visit == tp)
  
  ph1_var = ifelse(tp==two_timepoints[1], "ph1.D29", "ph1.D57")
  ph2_var = ifelse(tp==two_timepoints[1], "ph2.D29", "ph2.D57")
  wt_var = ifelse(tp==two_timepoints[1], "wt.D29", "wt.D57")
  
  # Subset the data to “phase 1 ptids” for the correlates
  rr3 <- rr3 %>% filter((!!sym(ph1_var))==1)
  
  # define case/non case flag based on the time point in the loop
  if (tp==two_timepoints[1]) {
    rr3 <- rr3 %>%
      mutate(case_flag = ifelse(Perprotocol==1 & EarlyendpointD29==0 & TwophasesampIndD29==1 & EventIndPrimaryD29==1, "Cases", ifelse(Perprotocol==1 & EarlyendpointD57==0 & TwophasesampIndD57==1 & EventIndPrimaryD1==0, "Non_cases_Control", NA)))
               
    } else if (tp==two_timepoints[2]){
      rr3 <- rr3 %>%
        mutate(case_flag = ifelse(Perprotocol==1 & EarlyendpointD57==0 & TwophasesampIndD57==1 & EventIndPrimaryD57==1, "Cases", ifelse(Perprotocol==1 & EarlyendpointD57==0 & TwophasesampIndD57==1 & EventIndPrimaryD1==0, "Non_cases_Control", NA)))
  }
   
  design <- twophase(id = list(~Ptid, ~ Ptid), strata = list(NULL, ~ Wstratum), weights = list(NULL, ~eval(as.name(wt_var))), method="simple", subset=~eval(as.name(ph2_var)), data = rr3)
  
  mod = svyby(~readout_trunc, ~Visit+case_flag+Marker+Baseline+Trt_lb, design, svymean, na.rm=T)
  conf = confint(mod)
  colnames(conf) = c("ci_l", "ci_u")
  mod = cbind(mod, conf)
  
  rr3_mag <- rr3 %>% filter((!!sym(ph2_var))==1 & !is.na(readout_trunc) & !is.na(case_flag)) %>%
    group_by_at(c("Visit","Baseline","Trt_lb", "case_flag","Marker")) %>%
    summarise(N=n()) %>%
    left_join(mod, by=c("Visit","Baseline","Trt_lb","case_flag","Marker")) %>%
    mutate(GMT = paste0(decimal_f(10^readout_trunc, 2),"\n(", decimal_f(10^ci_l, 2),", ", decimal_f(10^ci_u,2),")")) %>%
    select(Visit, Baseline, Trt_lb, case_flag, Marker, N, GMT) %>%
    pivot_wider(names_from=case_flag,values_from=c(N,GMT))
  
  rr3_mag_list[[ind]] <- rr3_mag
  
  ind=ind+1
  }
}
rr3_mag_all <- do.call("rbind", rr3_mag_list)

# rate diff
ind=1
rr3_ratediff_list=list()
for (mk in c("Anti N IgG (IU/ml)","Anti RBD IgG (IU/ml)","Anti Spike IgG (IU/ml)","Pseudovirus-nAb ID50","Pseudovirus-nAb ID80")){
  for (tp in two_timepoints){

  rr3 <- dat.long %>% filter(Marker == mk & Visit == tp)
  
  ph1_var = ifelse(tp==two_timepoints[1], "ph1.D29", "ph1.D57")
  ph2_var = ifelse(tp==two_timepoints[1], "ph2.D29", "ph2.D57")
  wt_var = ifelse(tp==two_timepoints[1], "wt.D29", "wt.D57")
  
  # Subset the data to “phase 1 ptids” for the correlates
  rr3 <- rr3 %>% filter((!!sym(ph1_var))==1)
  
  # define case/non case flag based on the time point in the loop
  if (tp==two_timepoints[1]) {
    rr3 <- rr3 %>%
      mutate(case_flag = ifelse(Perprotocol==1 & EarlyendpointD29==0 & TwophasesampIndD29==1 & EventIndPrimaryD29==1, "Cases", ifelse(Perprotocol==1 & EarlyendpointD57==0 & TwophasesampIndD57==1 & EventIndPrimaryD1==0, "Non_cases_Control", NA)))
               
    } else if (tp==two_timepoints[2]){
      rr3 <- rr3 %>%
        mutate(case_flag = ifelse(Perprotocol==1 & EarlyendpointD57==0 & TwophasesampIndD57==1 & EventIndPrimaryD57==1, "Cases", ifelse(Perprotocol==1 & EarlyendpointD57==0 & TwophasesampIndD57==1 & EventIndPrimaryD1==0, "Non_cases_Control", NA)))
  }

  design <- twophase(id = list(~Ptid, ~ Ptid), strata = list(NULL, ~ Wstratum), weights = list(NULL, ~eval(as.name(wt_var))), method="simple", subset=~eval(as.name(ph2_var)), data = rr3)
  
  mod <- svyby(~response, ~Visit+case_flag+Marker+Baseline+Trt_lb, design, survey::svyciprop, ci=TRUE, vartype="ci", na.rm=T)
  
  rr3_ratediff <- mod %>%
    pivot_wider(names_from = case_flag, values_from = c(response:ci_u)) %>%
    rowwise() %>% 
    mutate(rrdiff=paste0(round((response_Cases-response_Non_cases_Control),2),
                       "\n(", round((response_Cases-response_Non_cases_Control-sqrt((response_Cases-ci_l_Cases)^2+(ci_u_Non_cases_Control-response_Non_cases_Control)^2)),2),", ", round((response_Cases-response_Non_cases_Control+sqrt((response_Non_cases_Control-ci_l_Non_cases_Control)^2+(ci_u_Cases-response_Cases)^2)),2),")")) %>%
    select(Visit, Marker, Baseline, Trt_lb, rrdiff)
  
  rr3_ratediff_list[[ind]] <- rr3_ratediff
  
  ind=ind+1
  }
}
rr3_ratediff_all <- do.call("rbind", rr3_ratediff_list)


# for magnitude ratio between positive and negative
ind=1
rr3_magdiff_list=list()
for (mk in c("Anti N IgG (IU/ml)","Anti RBD IgG (IU/ml)","Anti Spike IgG (IU/ml)","Pseudovirus-nAb ID50","Pseudovirus-nAb ID80")){
  for (tp in two_timepoints){
    
  rr3 <- dat.long %>% filter(Marker == mk & Visit == tp)
  
  ph1_var = ifelse(tp==two_timepoints[1], "ph1.D29", "ph1.D57")
  ph2_var = ifelse(tp==two_timepoints[1], "ph2.D29", "ph2.D57")
  wt_var = ifelse(tp==two_timepoints[1], "wt.D29", "wt.D57")
  
  # Subset the data to “phase 1 ptids” for the correlates
  rr3 <- rr3 %>% filter((!!sym(ph1_var))==1)
  
  # define case/non case flag based on the time point in the loop
  if (tp==two_timepoints[1]) {
    rr3 <- rr3 %>%
      mutate(case_flag = ifelse(Perprotocol==1 & EarlyendpointD29==0 & TwophasesampIndD29==1 & EventIndPrimaryD29==1, "Cases", ifelse(Perprotocol==1 & EarlyendpointD57==0 & TwophasesampIndD57==1 & EventIndPrimaryD1==0, "Non_cases_Control", NA)))
               
    } else if (tp==two_timepoints[2]){
      rr3 <- rr3 %>%
        mutate(case_flag = ifelse(Perprotocol==1 & EarlyendpointD57==0 & TwophasesampIndD57==1 & EventIndPrimaryD57==1, "Cases", ifelse(Perprotocol==1 & EarlyendpointD57==0 & TwophasesampIndD57==1 & EventIndPrimaryD1==0, "Non_cases_Control", NA)))
  }
  
  design <- twophase(id = list(~Ptid, ~ Ptid), strata = list(NULL, ~ Wstratum), weights = list(NULL, ~eval(as.name(wt_var))), method="simple", subset=~eval(as.name(ph2_var)), data = rr3)
  
  mod <- svyby(readout_trunc ~ case_flag, ~Visit+Trt_lb+Baseline+Marker, design, svyglm, vartype="ci")
  
  rr3_magdiff <- mod %>% 
    rowwise() %>%
    mutate(`Ratios of GMT`=paste0(decimal_f(10^-case_flagNon_cases_Control,2),"\n(",decimal_f(10^-ci_u.case_flagNon_cases_Control,2),", ",decimal_f(10^-ci_l.case_flagNon_cases_Control,2),")")) %>%
    select(1,2,3,4,11)
  
  rr3_magdiff_list[[ind]] <- rr3_magdiff
  
  ind=ind+1
  }
}
rr3_magdiff_all <- do.call("rbind", rr3_magdiff_list)

# comparison
case_combine <- rr3_rate_all %>%
  left_join(rr3_mag_all, by=c("Visit", "Marker", "Baseline","Trt_lb","N_Non_cases_Control","N_Cases")) %>%
  left_join(rr3_ratediff_all, by=c("Visit","Baseline","Trt_lb","Marker")) %>%
  left_join(rr3_magdiff_all, by=c("Visit","Baseline","Trt_lb","Marker")) %>%
  rename_with(~ gsub("GMT","GMT/GMC",.x)) %>%
  rename_with(~ gsub("Non_cases_Control","Non-Cases",.x))

case_vacc_neg_v <- case_combine %>%
  filter((Baseline=="Negative" & Trt_lb=="Vaccine")) %>% ungroup() %>% select(1,4,5,7,9,6,8,10,11,12) %>% mutate_all(as.character)

case_vacc_pos_v <- case_combine %>%
  filter((Baseline=="Positive" & Trt_lb=="Vaccine")) %>% ungroup() %>% select(1,4,5,7,9,6,8,10,11,12) %>% mutate_all(as.character)

case_plcb_pos_v <- case_combine %>%
  filter((Baseline=="Positive" & Trt_lb=="Placebo")) %>% ungroup() %>% select(1,4,5,7,9,6,8,10,11,12) %>% mutate_all(as.character)

case_vacc_neg_v <- case_vacc_neg[, c("Visit","Marker")] %>%
  left_join(case_vacc_neg_v, by=c("Visit","Marker"))

case_vacc_pos_v <- case_vacc_pos[, c("Visit","Marker")] %>%
  left_join(case_vacc_pos_v, by=c("Visit","Marker"))

case_plcb_pos_v <- case_plcb_pos[, c("Visit","Marker")] %>%
  left_join(case_plcb_pos_v, by=c("Visit","Marker"))

testthat::expect_equal(case_vacc_neg, case_vacc_neg_v)
testthat::expect_equal(case_vacc_pos, case_vacc_pos_v)
testthat::expect_equal(case_plcb_pos, case_plcb_pos_v)

save(case_vacc_neg_v, file = here::here("verification", "verification_output", "cor_case_vacc_neg_v.Rdata"))

save(case_vacc_pos_v, file = here::here("verification", "verification_output", "cor_case_vacc_pos_v.Rdata"))

save(case_plcb_pos_v, file = here::here("verification", "verification_output", "cor_case_plcb_pos_v.Rdata"))
```
