---
output:
  pdf_document: default
  html_document: default
---
# Correlates of Risk Table Verification Documentation

This document indicates the script, author, verification script, and verification author of the files contained within the parent folder. The two scripts use the same base mock data. To verify the tables generated in the original scripts, all the tables were re-created and their values compared. Only when they all matched was it marked as verified accepted.

## Original Scripts

The scripts used to generate the original outputs. These live within the `immuno_tabular/code` folder.

----
- Script: code/make_functions.R
- Author(s): Chenchen Yu, Kendric Li, Nima Hejazi, David Benkeser
- Last Edit Date: January 21, 2021
- Description:

----
- Script: code/make_clean_data.R
- Author(s): Chenchen Yu, Kendric Li, Nima Hejazi, David Benkeser
- Last Edit Date: January 21, 2021
- Description:

----
- Script: code/make_table_all.R
- Author(s): Chenchen Yu, Kendric Li, Nima Hejazi, David Benkeser
- Last Edit Date: January 21, 2021
- Description:

## Verification Scripts

The scripts used to verify the outputs of the original outputs. These live within the `immuno_tabular/verification` folder.

----
Verification Script: cor_table_verification.R
Verification Author: Yiwen Lu
Verification Date: April 15, 2021
Verification Description: compare all numbers in each table generated by production code and verificadtion code to make sure they all match.