---
output: pdf_document
header-includes:
    - \usepackage{caption}
    - \usepackage{geometry}
    - \usepackage{pdflscape}
geometry: "top=0.1in, bottom=0.1in"

---

#  Tabular Description of Immunogenicity Data {#immuno-tabular}
\begin{landscape}
\captionsetup{justification=raggedright,singlelinecheck=false}
```{r knitr, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(kableExtra)
library(dplyr)
here::i_am("immuno_tabular/report.Rmd")
base::load(here::here( "immuno_tabular", "output", "Tables.Rdata"))
source(here::here("immuno_tabular", "code", "make_functions.R"))

```
\captionsetup[table]{labelformat=empty}
```{r tabs, results="asis", echo=FALSE, message=FALSE, warning=FALSE}
opts <- options(knitr.kable.NA = "")
for (i in 1:length(tlf)){
  subnum <- 0
  tlf_labels <- tlf[[i]]

  title_i <- tlf_labels[["table_header"]]
  footer_i <- tlf_labels[["table_footer"]]
  tlf_args <- names(tlf_labels)
  
  tab <- get(names(tlf)[i]) 
  tab <- data.frame(sapply(tab,function(x)gsub("%", "\\\\%", x)), check.names = F)
  colnames(tab) <- gsub("%", "\\\\%", colnames(tab))
  
  deselect <- if ("deselect" %in% tlf_args) tlf_labels[["deselect"]] else NA
  loop <- if ("loop" %in% tlf_args) tlf_labels[["loop"]] else NA
  group_table_col <- if ("group_table_col" %in% tlf_args) {
    tlf_labels[["group_table_col"]] 
    } else NA 
  
  if ("pack_row" %in% tlf_args) {
    pack_row <- tlf_labels[["pack_row"]]
    if (!is.na(loop)) { 
      pack_row_ind <- by(tab, 
                         tab[, loop], 
                         function(x)table(droplevels(x[, pack_row])))
      } else {
      pack_row_ind <- table(droplevels(tab[, pack_row]))  
      }
    } else NA
  
  col_name <- if ("col_name" %in% tlf_args) { 
    tlf_labels[["col_name"]] 
  } else setdiff(names(tab), deselect) 
  
  
  if (!is.na(loop)) {
    
    jloop <- pull(tab, !!as.name(loop)) %>% unique()
    
    for (j in jloop) {
      subnum <- subnum + 1
      tab.j <- dplyr::filter(tab, !!as.name(loop) == j) %>% 
        mutate_all(linebreak, align = "l")
      
      tabjk <- kable(tab.j %>% select(-!!deselect),
                     align = "l",
                     format = "latex",
                     booktabs = TRUE,
                     longtable = TRUE,
                     escape = FALSE,
                     col.names = linebreak(col_name, align="l"),
                     caption = sprintf("Table %s%s. %s by %s", i,
                                       letters[subnum], title_i, j)
                     ) %>%
        column_spec(1, width="2.7cm") %>% 
        kable_styling(latex_options = "repeat_header") %>%
        footnote(general_title = "", general = footer_i, threeparttable = TRUE,
        escape = FALSE)

        if ("header_above1" %in% tlf_args) {
          tabjk <-add_header_above(tabjk, tlf_labels[["header_above1"]])
          }
        
        if ("header_above2" %in% tlf_args) {
          tabjk <-add_header_above(tabjk, tlf_labels[["header_above2"]])
          }
      
        if ("pack_row" %in% tlf_args) {
          tabjk <- pack_rows(tabjk, index = pack_row_ind[j])
         }
    print(tabjk)
    cat("\n\n\\clearpage\n")
    }
    
    } else {
      
      tab <- mutate_all(tab, linebreak, align = "l") 
      tabk <- kable(
        if (is.na(deselect)) {tab} else {tab %>% select(-!!deselect)},
        align = "l",
        format = "latex",
        booktabs = TRUE,
        longtable = TRUE,
        escape = FALSE,
        col.names = linebreak(col_name, align="l"),
        caption = sprintf("Table %s. %s", i, title_i)) %>%
            column_spec(1, width="2.7cm") %>% 
        kable_styling(latex_options = "repeat_header") %>%
        footnote(general_title = "", general = footer_i,
        threeparttable = TRUE, escape = FALSE)
      
       if ("header_above1" %in% tlf_args) {
          tabk <- add_header_above(tabk, tlf_labels[["header_above1"]])
          }
        
      if ("header_above2" %in% tlf_args) {
          tabk <- add_header_above(tabk, tlf_labels[["header_above2"]])
          }

      if ("pack_row" %in% tlf_args) {
        tabk <- pack_rows(tabk, index = pack_row_ind)
        }
      print(tabk)
      cat("\n\n\\clearpage\n")
}

}

```
\end{landscape}