---
title: Verification Plan for Immunogenicity Tables
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

Project directory: `correlates_reporting/immuno_tabular`

Specifications:

Other Background Information: N/A

### Verification  Sign-Off

```{r signatures, echo = FALSE, message = FALSE, tidy = FALSE, cache = FALSE, results = 'asis'}
library(knitr)
library(kableExtra)
library(tibble)

options(kableExtra.latex.load_packages = FALSE, 
        knitr.table.format = "latex",
        knitr.kable.NA = '',
        width = 40,
        usethis.quiet = TRUE)

signature_table <- function(people){
  # check that the tables have correct variables
  if (!all(c("role", "name") %in% tolower(names(people)))) {
    stop(paste0("people table must have variables: role and name. ",
                "Contains: ", paste0(tolower(names(people)), collapse = ", ")))
  }
  
  people$signature <- NA
  people$date <- NA
  names(people) <- tolower(names(people))
  people[, c("role", "name", "signature", "date")] %>% 
  kable(col.names = c("Role", "Name", "Signature", "Date"),
        escape = FALSE, booktabs = FALSE) %>% 
    kable_styling(full_width = FALSE, position = "left") %>% 
    row_spec(0, background = rgb(184, 204, 228, maxColorValue = 255)) %>% 
    column_spec(1, width = "9em", border_left = TRUE) %>% 
    column_spec(2, width = "11em") %>% 
    column_spec(3, width = "15em") %>% 
    column_spec(4, width = "8em", border_right = TRUE)
}

tibble::tribble(
  ~ name,                ~ role,
  "Dr. Peter Gilbert",  "Manager",
  "Dr. David Benkeser", "Programmer",
  "Nima Hejazi",        "Programmer",
  "Chenchen Yu",        "Specifier/Programmer",
  "Yiwen Lu",         "Tester" 
) %>% 
  signature_table()

```

## Verification Procedure

Verification for the immunogenicity tables generated in support of the CoVPN correlates will be based on a risked based approach. Risk of a table is determined by importance: whether it will be used to drive decision making. Tables that are determined to have high importance, thus high risk, will go through independent double programming. If a table is decided to have low risk, it will be verified via code review, not through independent double programming. A table will be verified by someone other than the original programmer (the tester). 

For independent double programming, the tester will independently generate the same table based on the tables specification. They will then programmatically verify the values presented in the original table match the ones generated by the verification code, and produce an output file that shows that the results match. 

For code review, the tester will review the programmers code directly from the code folder. The review will consist of checking the programming logic of the code for consistency with the specifications, verifying the assumptions in the source data. The tester will confirm that the code does not produce errors or unexpected warnings, check the output for nonsensical or unexpected results, and finally review the output headers, footers and formatting for consistency.

All tables generated by code in the `immuno_tabular` folder are determined to be high risk, and thus will all be independently double programmed.

Mock data used in the verification can be found in the `COVIDcorr` R package, available at https://github.com/CoVPN/correlates_mockdata. Any use of this code outside of the mock data is not guaranteed and is subject to additional verification.

### Verification Assignments

The verification results will be contained in `verification_report.pdf`, where the results of the independent verification will be reported. It will contain a table that lists the table generated, the original source code filename, the verification code filename, the results of the comparison, and the date the testing is completed.

