---
title: "COVID correlates analysis report CoR"
shorttitle: "COVID correlates analysis CoR"
author:
header-includes:
   - \usepackage{float}
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2:
    citation_package: natbib
    number_sections: true
    extra_dependencies: ["caption", "subcaption", "graphicx"]
    toc: false
linkcolor: blue
bibliography: ref.bib
---

```{r, include=FALSE}
source(here::here("..", "_common.R"), local = knitr::knit_global())
```
<!-- Note that there is no need to source _common.R in report.Rmd because it is taken care of elsewhere in yml -->


\counterwithin{table}{section}
\counterwithin{figure}{section}


<!-- these latex variables are used in report_sub -->
\newif\ifCOVE
\newif\ifENSEMBLE
`r paste0("\\", study_name_code, "true")` 


<!-- COVE -->

```{r, echo=FALSE, results='asis'}
if (study_name_code=="COVE") {
  for (i in 1:2) {
    tpeak <- ifelse(i==1, 29, 57)
    COR <- paste0("D", tpeak)
    special.note=""
    pathCoRoutput <- paste0("output/", attr(config,"config"), "/", COR)
    res = knitr::knit_child(c(here::here('.', 'report_sub.Rmd')), quiet = TRUE)
    cat(res, sep = '\n')
    cat("\\clearpage", sep = '\n')
  }
}
```




<!-- ENSEMBLE -->

```{r, echo=FALSE, results='asis'}
if (study_name_code=="ENSEMBLE") {
  for (i in 1:2) {
    tpeak <- 29
    COR <- ifelse(i==1, "D29", "D29start1")
    special.note = paste0("$\\ddagger$ Count cases starting ", ifelse(i==1,7,1), " days post Day 29.")
    pathCoRoutput <- paste0("output/", attr(config,"config"), "/", COR)
    res = knitr::knit_child(c(here::here('.', 'report_sub.Rmd')), quiet = TRUE)
    cat(res, sep = '\n')
    cat("\\clearpage", sep = '\n')
  }
}
```





