---
title: "COVID correlates analysis report Nonlinear CoR"
shorttitle: "COVID correlates analysis Nonlinear CoR"
author:
header-includes:
   - \usepackage{float}
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2:
    citation_package: natbib
    number_sections: true
    extra_dependencies: ["caption", "subcaption", "graphicx"]
    toc: false
linkcolor: blue
bibliography: ref.bib
---

```{r, include=FALSE}
source(here::here("..", "_common.R"), local = knitr::knit_global())
```
<!-- Note that there is no need to source _common.R in report.Rmd because it is taken care of elsewhere in yml -->


\counterwithin{table}{section}
\counterwithin{figure}{section}


```{r, echo=FALSE}
Day <- 57
pathCoRoutput <- paste0("output/D57")
pathCorcoxphOutput <- paste0("../cor_coxph/output/", attr(config,"config"), "/PrimaryD57")
```

```{r, child=if(has57) c(here::here('.', 'report_sub.Rmd'))}
```

\clearpage


```{r, echo=FALSE}
Day <- 29
pathCoRoutput <- paste0("output/D29")
pathCorcoxphOutput <- paste0("../cor_coxph/output/", attr(config,"config"), "/PrimaryD29")
```

```{r, child=if(has29) c(here::here('.', 'report_sub.Rmd'))}
```
